services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: project_base

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - base

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8765:8765"
    depends_on:
      - base
