services:
  detect:
    build:
      context: .
      dockerfile: web.Dockerfile
    develop:
      watch:
        - path: ./web
          target: /web
          action: sync+restart
    networks:
      - proxy

  detect-api:
    build:
      context: .
      dockerfile: api.Dockerfile
    develop:
      watch:
        - path: ./api
          target: /api
          action: sync+restart
    networks:
      - proxy

networks:
  proxy:
    name: cicd_proxy
    external: true
